name: Build and deploy WeaponBot
on:
  push:
    branches: [ master ]

env:
  discord_token: ${{ secrets.DISCORD_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.11 ]

    steps:
      - uses: actions/checkout@master

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create environment file
        run: |
          touch .env
          echo DISCORD_TOKEN=${{ env.discord_token }} >> .env
          cat .env

      - name: Build
        run: npm run build

      - name: Upload files
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: sftp
          remote-host: ${{ secrets.FTP_HOST }}
          remote-user: ${{ secrets.FTP_USER }}
          remote-password: ${{ secrets.FTP_PASSWORD }}
          remote-path: /home/container
          remote-port: ${{ secrets.FTP_PORT }}
