name: Build and upload WeaponBot
on:
  push:
    branches: [ master ]

env:
  discord_token: ${{ secrets.DISCORD_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.11 ]

    steps:
      - name: Checkout App
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create environment file
        run: |
          touch .env
          echo DISCORD_TOKEN=${{ env.discord_token }} >> .env
          cat .env

      - name: Build
        run: npm run build


      - name: Upload file
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: "sftp"
          remote-host: "${{ secrets.FTP_HOST }}"
          remote-user: "${{ secrets.FTP_USER }}"
          remote-password: "${{ secrets.FTP_PASSWORD }}"
          remote-port: "${{ secrets.FTP_PORT }}"
          remote-path: "/."
          sync: "full"