name: Build and deploy WeaponBot
on:
  push:
    branches: [ master ]

env:
  discord_token: ${{ secrets.DISCORD_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.11 ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create environment file
        run: |
          touch .env
          echo DISCORD_TOKEN=${{ env.discord_token }} >> .env
          cat .env

      - name: Build
        run: npm run build

      - name: Deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server: ${{ secrets.FTP_SERVER }}
          port: ${{ secrets.FTP_PORT }}
          remote_path: '/'
          sftp_only: true
          delete_remote_files: true
